### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by v1m** [distributedweaknessfiling/dwf-workflow#9]
1. Will DWF project track the mapping between DWFs and Mitre-CVEs?
scenario: a DWF ID was issued to an issue, days/months later a CVE ID (Mitre-ecosystem CVE) was assigned to the same exact issue (enough details were available to accurately determine that both IDs are for the same issue).

> If requester is on the allow list, a CVE is assigned, the issue is closed  

2. What is an "allow list"?

2.a What if an established user changes their github profile?
2.b What if github goes away (or becomes restricted in its use in some way)?!!!!
2.c what if github is blocked in a country/region/IP-space from which a user wants to submit?

3. How do we stop potential scammers from just creating a host of false issues (perhaps via multiple throwaway github accounts)?

4. Is there a concept of retiring DWF_IDs? (I guess not)

5. < fun > LOL.... we should charge "something" (donation of service or money) from requesters who want to request for a particular set of numbers in their DWF_ID :) </ fun >

**Comment by kurtseifried** [comment]
> 1. Will DWF project track the mapping between DWFs and Mitre-CVEs?
>    scenario: a DWF ID was issued to an issue, days/months later a CVE ID (Mitre-ecosystem CVE) was assigned to the same exact issue (enough details were available to accurately determine that both IDs are for the same issue).

Assuming the legacy CVE ID issued by MITRE is correct then the DWF CVE ID will generally be marked as a DUPLICATE.

> > If requester is on the allow list, a CVE is assigned, the issue is closed
> 
> 1. What is an "allow list"?

A list of people allowed to request DWF CVE IDs without review e.g. trusted contributors.
 
> 2.a What if an established user changes their github profile?

I don't understand the question. If they change it then they change it. This isn't really a concern for us.

> 2.b What if github goes away (or becomes restricted in its use in some way)?!!!!

We'll move to another hosting solution.

> 2.c what if github is blocked in a country/region/IP-space from which a user wants to submit?

Then users can use a VPN/etc to access it. We can't be responsible for global politics. 

> 
> 1. How do we stop potential scammers from just creating a host of false issues (perhaps via multiple throwaway github accounts)?

The review process prevents this. Also DWF CVE IDs can be reviewed and REJECT'ed by the community at large. 

> 2. Is there a concept of retiring DWF_IDs? (I guess not)

What does "retiring" mean?

> 3. < fun > LOL.... we should charge "something" (donation of service or money) from requesters who want to request for a particular set of numbers in their DWF_ID :) </ fun >

No. We are not creating artificial barriers to entry. We want to be an inclusive community.

**Comment by joshbressers** [comment]
We need to add these to the FAQ with a bit more nuance I think. I'll assign it to myself

**Comment by v1m** [comment]
2.a What if an established user changes their github profile?

I guess there will be a requirement for some mechanism to transfer "established trust" over from old_github_profile to new_github_profile. But perhaps that will just complicate things.

**Comment by jonasbb** [comment]
> > 2.a What if an established user changes their github profile?
> 
> I don't understand the question. If they change it then they change it. This isn't really a concern for us.

GitHub allows changing usernames and also re-using old usernames. This is relevant because the allow list file only contains usernames but not stable identifiers.
Now you can have a user `A` which gets added to the allow list. After some point `A` renames their account to `B`. Now somebody can snatch the `A` username again, either by renaming their account or creating a new account and immediately gaining the permissions attached to the allow list.

For reference here is GitHubs policy on account renames: https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-github-username
> After changing your username, your old username becomes available for anyone else to claim.

**Comment by joshbressers** [comment]
It looks like there is an id field we can capture.

I had no idea how much pain it would be to change a username :)

Thanks for this

**Comment by kurtseifried** [comment]
> > > 2.a What if an established user changes their github profile?
> > 
> > 
> > I don't understand the question. If they change it then they change it. This isn't really a concern for us.
> 
> GitHub allows changing usernames and also re-using old usernames. This is relevant because the allow list file only contains usernames but not stable identifiers.
> Now you can have a user `A` which gets added to the allow list. After some point `A` renames their account to `B`. Now somebody can snatch the `A` username again, either by renaming their account or creating a new account and immediately gaining the permissions attached to the allow list.
> 
> For reference here is GitHubs policy on account renames: https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-github-username
> 
> > After changing your username, your old username becomes available for anyone else to claim.

So this is part of a larger question:

What do we do (if anything) when control of a github username changes, e.g. they change their name and someone else takes it, or they sell their account, or an attacker hijacks their account?

Specifically tracking just username changes is not sufficient to deal with the above. What we need is generally robust processes to detect malicious behavior, e.g. spamming DWF CVE IDs, so part of this is once a user is put on the allow list what can result in them getting kicked off? One aspect of this is the "Review" label/issue: https://github.com/distributedweaknessfiling/dwf-workflow/issues/5 and the "Disputed" label/issue: https://github.com/distributedweaknessfiling/dwf-workflow/issues/4 as well as "who owns the DWF CVE ID?" issue: https://github.com/distributedweaknessfiling/dwf-workflow/issues/6

**Comment by v1m** [comment]
> What does "retiring" mean?
I meant invalidating an entry by marking it as invalid within the data schema.
scenario: 
a. user introduces a typo and then reports back to the project about the typo.
b. user submits multiple issues, and then realizes that all of them are from the same root issue. (so just one DWF-CVE is enough)
c. due to an oversight, duplicate DWF-CVEs get created
d. spam DWF-CVEs make their way into the database.

**Comment by kurtseifried** [comment]
> > What does "retiring" mean?
> 
> I meant invalidating an entry by marking it as invalid within the data schema.
> scenario:
> a. user introduces a typo and then reports back to the project about the typo.
> b. user submits multiple issues, and then realizes that all of them are from the same root issue. (so just one DWF-CVE is enough)
> c. due to an oversight, duplicate DWF-CVEs get created
> d. spam DWF-CVEs make their way into the database.

That's already covered by the REJECT state.

**Comment by v1m** [comment]
In a dispute between a security researcher and a vendor, how does one validate that the github profile of an entity:

- is the real/valid vendor entity? 
- is the entity which can speak on behalf of the vendor?

**Comment by kurtseifried** [comment]
> In a dispute between a security researcher and a vendor, how does one validate that the github profile of an entity:
> 
> * is the real/valid vendor entity?
> * is the entity which can speak on behalf of the vendor?

We don't have to really. A third party can also bring up concerns, or defend against them, or whatever. They can make statements, which will need to be backed up by evidence.

As for someone claiming to speak for/as a vendor I don't think we're going to have a lot of impersonators, and it's always easy to check via their public profile or email.

**Comment by kurtseifried** [comment]
As per comment in https://github.com/distributedweaknessfiling/dwf-workflow/issues/18

One addendum: we don't mark it as a duplicate until it's published in the NVD database.
